### PR TITLE
Feature/update map view for search results

### PR DESCRIPTION
**Pull request by seanjessen**
### Summary
https://trello.com/c/5kbfW4cU/126-update-map-view-for-search-results

The map view has been updated to include new functionality as outlined in the ticket above

### Development checklist
- [x] Clicking on a map marker should add an active icon to the marker and should also select the relevant service in the list to the left of the map
- [x] Click on a list item in the left should highlight this as active and also highlight the relevant map marker
- [x] The map and list should take advantage of the available space and the list should scroll for overflow
- [x] Clicking view more on a service takes you to the relevant service page

### Release checklist
N/A

### Notes
N/A

### CODE REVIEW

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
I'm getting the following two errors when testing.

Also, does the code handle locations with no lat/lon? 

Screenshot 2020-10-07 at 22 31 37
Screenshot 2020-10-07 at 22 29 39

**Comment by seanjessen** [comment]
> I'm getting the following two errors when testing.
> 
> Also, does the code handle locations with no lat/lon?
> 
> Screenshot 2020-10-07 at 22 31 37
> 
> Screenshot 2020-10-07 at 22 29 39

@matthew-inamdar - I've fixed these errors now and also added in a conditional check for a returned location

**Comment by matthew-inamdar** [comment]
Hey @seanjessen - I'm still getting the duplicate keys error in the console?

Screenshot 2020-10-12 at 08 54 14

**Comment by seanjessen** [comment]
> Hey @seanjessen - I'm still getting the duplicate keys error in the console?
> 
> I get this error on page load, as well as when I click on a service card on the list listing.
> 
> Screenshot 2020-10-12 at 08 54 14

@matthew-inamdar I've fixed the duplicate key error now

**Pull request merged**
